name: Deploy existing Sphinx docs to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write

    steps:
      - uses: actions/checkout@v4

      # Pas besoin de setup Python ou d'installer des dépendances puisque nous ne faisons pas de build

      # Copier le contenu de /pixx_doc/html vers un dossier 'public' si nécessaire ou ajuster le chemin ci-dessous si différent
      - name: Prepare docs
        run: |
          mkdir -p public
          cp -r pixx_doc/html/* public/
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          path: public
