name: Deploy existing Sphinx docs to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Prepare docs
        run: |
          mkdir -p public
          cp -r pixx_doc/html/* public/
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          path: public
